name: Deploy Frontend

on:
    push:
        branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@v3

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Upload to storage'
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name wodyaresume02 --auth-mode key -d '$web' -s . --overwrite
